### ISSUE TITLE
Label Text and BackgroundColor breaks

### ISSUE THREAD

**Issue by reddvid** [MicrosoftDocs/mslearn-dotnetmaui-customize-xaml-pages-layout#1]
I tested the sample exercise1 project on a mac as a macCatalyst app and as iOS on an emulator. After playing with the app, the label shows unintended results:

1) The BackgroundColor become separated with the Text
2) The text is nowhere to be found

Both UI issues resolves automatically when the window loses focus (MacCatalyst app) or app switching in iOS

Unit 3 in Customize layout in .NET MAUI XAML page.

![Screen Shot 2022-06-12 at 01 17 31](https://user-images.githubusercontent.com/6512079/173197985-c2f3d079-27cf-4d85-bac3-1869e4296437.png)
![Screen Shot 2022-06-12 at 01 19 18](https://user-images.githubusercontent.com/6512079/173198052-6c7f5f28-33e2-45bd-968a-89cebb4ff4be.png)

**Comment by codemillmatt** [comment]
Thanks for the info @reddvid, I'm also seeing the same issue.

@davidortinau - fyi on this.
