### ISSUE TITLE
Android App not behaving as expected

### ISSUE THREAD

**Issue by statecb** [MicrosoftDocs/mslearn-dotnetmaui-customize-xaml-pages-layout#2]
UPDATE: This issue appears to be fixed as of VS 2022 Preview 5 - 17.3.5 - it could have been fixed in 3 or 4, but I went from 2 to 5 because I didn't have the time to troubleshoot installation problems with 3 and 4.

I'm not sure this is the proper place for this issue to be reported as it seems to be a Maui platform issue.  

Exercise #1:
The application works as expected in Windows, works in iOS (for the most part - some funky positioning of text vs background - simulator issue???) but the Android app does not refresh the screen - on button clicks.  The clicks are happening, the label is not responding to the change in Horizontal or Vertical options.

Environment:
VS 2022 Preview 3
No changes to source (clone and run).
Android Image: Pixel 5 - API 32 (Android 12.1 - API 32)
Android Image: Pixel 2 Q 10.0  - API 29 (Android 10.0 - API 29)

**Comment by dbrillon** [comment]
I reproduce the same problem.  
I'm using
- Visual Studio Community 2022 for Mac Preview
   Version 17.3 Preview (17.3 build 1038)

**Comment by jamesmontemagno** [comment]
Closing as fixed in .NET MAUI itself
