### ISSUE TITLE
These exercise are not running when I clone them.

### ISSUE THREAD

**Issue by BKNorton** [MicrosoftDocs/mslearn-dotnetmaui-customize-xaml-pages-layout#5]
After cloning this repository and trying to open and run Alignment in exercise1, I get the following error : "A debugger is attached to 'project.exe' but not configured to debug this unhandled exception, To debug this exception, detach the current debugger". I do not have this problem when I create my own .net maui projects. I am using visual studio 2022.

**Comment by jamesmontemagno** [comment]
Are you able to run without debugging? perhaps somethign is blocking the debug operation on your android emulator.

Have you tried windows?
